import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [
  index("routes/public-home.tsx"),
  layout("routes/docs.tsx", [
    route("docs", "routes/docs._index.tsx"),
    route("docs/:section/:page", "routes/docs.$section.$page.tsx"),
  ]),
  route("dashboard", "routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("verify-email", "routes/verify-email.tsx"),
  route("handover/accept", "routes/handover-accept.tsx"),
  route("profile", "routes/profile.tsx"),
  route("settings", "routes/settings.tsx"),
  route("logout", "routes/logout.tsx"),
  route("assets", "routes/assets.tsx"),
  route("admin/overview", "routes/admin.overview.tsx"),
  route("admin/users", "routes/admin.users.tsx"),
  route("admin/users/:userId", "routes/admin.users.$userId.tsx"),
  route("admin/assets", "routes/admin.assets.tsx"),
  route("admin/assets/print-qr", "routes/admin.assets.print-qr.tsx"),
  route("admin/assets/:assetId", "routes/admin.assets.$assetId.tsx"),
  route("admin/sites", "routes/admin.sites.tsx"),
  route("admin/sites/:siteId", "routes/admin.sites.$siteId.tsx"),
  route("admin/categories", "routes/admin.categories.tsx"),
  route("admin/manufacturers", "routes/admin.manufacturers.tsx"),
  route("admin/vendors", "routes/admin.vendors.tsx"),
  route("admin/reports", "routes/admin.reports.tsx"),
  route("admin/api-keys", "routes/admin.api-keys.tsx"),
  route("admin/webhooks", "routes/admin.webhooks.tsx"),
  route("admin/import-export", "routes/admin.import-export.tsx"),
  route("*", "routes/$.tsx"),
] satisfies RouteConfig;
