import PDFDocument from 'pdfkit';
import config from '@config/config';
import { ICustodyDocumentType } from '@domain/_interfaces/custodyDocument.interface';

export type CustodyLocale = 'en' | 'es';

export interface CustodyPdfAsset {
  id: string;
  name: string;
  model: string | null;
  serialNumber: string;
  categoryName: string | null;
  siteName: string | null;
  manufacturerName: string | null;
  vendorName: string | null;
}

export interface CustodyPdfData {
  type: ICustodyDocumentType;
  documentId: string;
  printDate: Date;
  handoverId: string | null;
  /** One or more assets covered by this receipt; rendered as a grid. */
  assets: CustodyPdfAsset[];
  employee: {
    name: string | null;
    email: string | null;
  };
  conditionAtHandover: string | null;
  accessoriesNote: string | null;
}

interface CustodyStrings {
  titleCheckout: string;
  titleCheckin: string;
  reference: string;
  documentId: string;
  printDate: string;
  handoverRef: string;
  assetRef: string;
  assetCount: (n: number) => string;
  partiesHeading: string;
  organization: string;
  employeeName: string;
  employeeEmail: string;
  assetHeading: string;
  assetName: string;
  model: string;
  serial: string;
  category: string;
  site: string;
  manufacturer: string;
  vendor: string;
  condition: string;
  accessories: string;
  termsHeading: string;
  terms: string[];
  signatureHeading: string;
  employeeColumn: string;
  representativeColumn: string;
  printedName: string;
  signature: string;
  date: string;
  footer: (app: string, iso: string) => string;
  notProvided: string;
}

const STRINGS: Record<CustodyLocale, CustodyStrings> = {
  en: {
    titleCheckout: 'Equipment Custody Receipt — Assignment',
    titleCheckin: 'Equipment Custody Receipt — Return',
    reference: 'Reference',
    documentId: 'Document ID',
    printDate: 'Date',
    handoverRef: 'Handover ref.',
    assetRef: 'Asset ref.',
    assetCount: (n) => `Assets: ${n}`,
    partiesHeading: 'Parties',
    organization: 'Organization',
    employeeName: 'Employee name',
    employeeEmail: 'Employee email',
    assetHeading: 'Asset details',
    assetName: 'Asset',
    model: 'Model',
    serial: 'Serial number',
    category: 'Category',
    site: 'Site / location',
    manufacturer: 'Manufacturer',
    vendor: 'Vendor',
    condition: 'Condition at handover',
    accessories: 'Accessories included',
    termsHeading: 'Terms',
    terms: [
      'The employee acknowledges receipt of the equipment described above in the stated condition.',
      'The employee agrees to use the equipment with due care and for work purposes.',
      'Loss, theft, or damage must be reported to IT without undue delay.',
      'The equipment remains the property of the organization and must be returned on request or upon termination of employment.',
      'The employee is responsible for safeguarding any data and credentials stored on the equipment.',
    ],
    signatureHeading: 'Signatures',
    employeeColumn: 'Employee',
    representativeColumn: 'Authorized representative (IT / Admin)',
    printedName: 'Printed name',
    signature: 'Signature',
    date: 'Date',
    footer: (app, iso) => `Generated by ${app} on ${iso}`,
    notProvided: '—',
  },
  es: {
    titleCheckout: 'Recibo de Custodia de Equipo — Asignación',
    titleCheckin: 'Recibo de Custodia de Equipo — Devolución',
    reference: 'Referencia',
    documentId: 'ID de documento',
    printDate: 'Fecha',
    handoverRef: 'Ref. de entrega',
    assetRef: 'Ref. de activo',
    assetCount: (n) => `Activos: ${n}`,
    partiesHeading: 'Partes',
    organization: 'Organización',
    employeeName: 'Nombre del empleado',
    employeeEmail: 'Correo del empleado',
    assetHeading: 'Detalles del activo',
    assetName: 'Activo',
    model: 'Modelo',
    serial: 'Número de serie',
    category: 'Categoría',
    site: 'Sede / ubicación',
    manufacturer: 'Fabricante',
    vendor: 'Proveedor',
    condition: 'Estado en la entrega',
    accessories: 'Accesorios incluidos',
    termsHeading: 'Términos',
    terms: [
      'El empleado confirma la recepción del equipo descrito arriba en el estado indicado.',
      'El empleado se compromete a usar el equipo con el debido cuidado y para fines laborales.',
      'La pérdida, robo o daño debe notificarse a TI sin demora indebida.',
      'El equipo sigue siendo propiedad de la organización y debe devolverse cuando se solicite o al finalizar la relación laboral.',
      'El empleado es responsable de proteger los datos y credenciales almacenados en el equipo.',
    ],
    signatureHeading: 'Firmas',
    employeeColumn: 'Empleado',
    representativeColumn: 'Representante autorizado (TI / Admin)',
    printedName: 'Nombre',
    signature: 'Firma',
    date: 'Fecha',
    footer: (app, iso) => `Generado por ${app} el ${iso}`,
    notProvided: '—',
  },
};

const PAGE_MARGIN = 50;

/**
 * Renders a printable custody receipt PDF and resolves with the complete byte
 * buffer. Layout is industry-style: header, reference, parties table, asset
 * table, terms, and a dual signature block.
 */
export function renderCustodyDocumentPdf(
  data: CustodyPdfData,
  locale: CustodyLocale = 'en',
): Promise<Buffer> {
  const t = STRINGS[locale] ?? STRINGS.en;
  const orgName = config.custody.orgName;

  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: PAGE_MARGIN });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const dash = t.notProvided;
    const fmtDate = (d: Date) => d.toISOString().slice(0, 10);

    // Header — organization name.
    doc.fontSize(18).font('Helvetica-Bold').text(orgName, { align: 'left' });
    doc.moveDown(0.3);

    // Document title.
    const title = data.type === ICustodyDocumentType.CHECK_OUT ? t.titleCheckout : t.titleCheckin;
    doc.fontSize(14).font('Helvetica-Bold').text(title);
    doc.moveDown(0.5);

    // Reference block.
    doc.fontSize(9).font('Helvetica').fillColor('#444');
    doc.text(`${t.documentId}: ${data.documentId}`);
    doc.text(`${t.printDate}: ${fmtDate(data.printDate)}`);
    if (data.handoverId) doc.text(`${t.handoverRef}: ${data.handoverId}`);
    // One asset keeps the original id reference; batches show a count instead.
    if (data.assets.length === 1) doc.text(`${t.assetRef}: ${data.assets[0].id}`);
    else doc.text(t.assetCount(data.assets.length));
    doc.fillColor('black');
    doc.moveDown(1);

    const labelWidth = 160;
    const renderRow = (label: string, value: string | null) => {
      const y = doc.y;
      doc.fontSize(10).font('Helvetica-Bold').text(label, PAGE_MARGIN, y, { width: labelWidth });
      doc
        .font('Helvetica')
        .text(value && value.length > 0 ? value : dash, PAGE_MARGIN + labelWidth, y, {
          width: doc.page.width - PAGE_MARGIN * 2 - labelWidth,
        });
      doc.moveDown(0.4);
    };

    const contentWidth = doc.page.width - PAGE_MARGIN * 2;
    const sectionHeading = (text: string) => {
      doc.moveDown(0.5);
      // Pass an explicit x: renderRow leaves the cursor indented at the value column,
      // which would otherwise shift (and clip) headings/paragraphs that follow.
      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .fillColor('#222')
        .text(text, PAGE_MARGIN, doc.y, { width: contentWidth });
      doc.fillColor('black').moveDown(0.4);
    };

    // Parties table.
    sectionHeading(t.partiesHeading);
    renderRow(t.organization, orgName);
    renderRow(t.employeeName, data.employee.name);
    renderRow(t.employeeEmail, data.employee.email);

    // Asset table — a grid with one row per asset. Column headers repeat on each
    // page so a long batch stays readable when it spills past the first page.
    sectionHeading(t.assetHeading);

    const gridCols: Array<{ label: string; value: (a: CustodyPdfAsset) => string | null; frac: number }> = [
      { label: t.assetName, value: (a) => a.name, frac: 0.28 },
      { label: t.model, value: (a) => a.model, frac: 0.17 },
      { label: t.serial, value: (a) => a.serialNumber, frac: 0.23 },
      { label: t.category, value: (a) => a.categoryName, frac: 0.16 },
      { label: t.site, value: (a) => a.siteName, frac: 0.16 },
    ];
    const cellPadX = 4;
    const rowPadY = 4;
    // Keep the grid clear of the footer band at the bottom of the page.
    const footerReserve = 40;
    const colWidths = gridCols.map((c) => c.frac * contentWidth);
    const colX: number[] = [];
    {
      let x = PAGE_MARGIN;
      for (const w of colWidths) {
        colX.push(x);
        x += w;
      }
    }

    const cellText = (v: string | null) => (v && v.length > 0 ? v : dash);

    const measureRow = (values: string[], bold: boolean): number => {
      doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(9);
      let max = 0;
      values.forEach((v, i) => {
        const h = doc.heightOfString(v, { width: colWidths[i] - cellPadX * 2 });
        if (h > max) max = h;
      });
      return max + rowPadY * 2;
    };

    const drawRow = (values: string[], bold: boolean) => {
      const h = measureRow(values, bold);
      const top = doc.y;
      doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(9).fillColor('black');
      values.forEach((v, i) => {
        doc.text(v, colX[i] + cellPadX, top + rowPadY, { width: colWidths[i] - cellPadX * 2 });
      });
      const bottom = top + h;
      doc
        .moveTo(PAGE_MARGIN, bottom)
        .lineTo(PAGE_MARGIN + contentWidth, bottom)
        .strokeColor(bold ? '#999' : '#e0e0e0')
        .stroke();
      doc.x = PAGE_MARGIN;
      doc.y = bottom;
    };

    const headerValues = gridCols.map((c) => c.label);
    const drawHeader = () => drawRow(headerValues, true);

    drawHeader();
    for (const asset of data.assets) {
      const values = gridCols.map((c) => cellText(c.value(asset)));
      const h = measureRow(values, false);
      if (doc.y + h > doc.page.height - PAGE_MARGIN - footerReserve) {
        doc.addPage();
        drawHeader();
      }
      drawRow(values, false);
    }

    // Shared condition / accessories apply to the whole batch.
    doc.moveDown(0.6);
    renderRow(t.condition, data.conditionAtHandover);
    renderRow(t.accessories, data.accessoriesNote);

    // Terms.
    sectionHeading(t.termsHeading);
    doc.fontSize(9).font('Helvetica');
    t.terms.forEach((clause) => {
      // Explicit x + width so each clause wraps inside the page (hanging indent
      // keeps continuation lines aligned past the bullet).
      doc.text(`•  ${clause}`, PAGE_MARGIN, doc.y, {
        width: contentWidth,
        align: 'left',
        indent: 0,
      });
      doc.moveDown(0.3);
    });

    // Signature block — two columns.
    sectionHeading(t.signatureHeading);
    const colGap = 30;
    const colWidth = (doc.page.width - PAGE_MARGIN * 2 - colGap) / 2;
    const leftX = PAGE_MARGIN;
    const rightX = PAGE_MARGIN + colWidth + colGap;
    const blockTop = doc.y + 10;

    const renderSignatureColumn = (x: number, heading: string) => {
      let y = blockTop;
      doc.fontSize(10).font('Helvetica-Bold').text(heading, x, y, { width: colWidth });
      y += 40;
      doc.font('Helvetica').fontSize(9);
      const line = (label: string) => {
        doc.moveTo(x, y).lineTo(x + colWidth, y).strokeColor('#999').stroke();
        doc.fillColor('#555').text(label, x, y + 3, { width: colWidth });
        doc.fillColor('black');
        y += 35;
      };
      line(t.printedName);
      line(t.signature);
      line(t.date);
    };

    renderSignatureColumn(leftX, t.employeeColumn);
    renderSignatureColumn(rightX, t.representativeColumn);

    // Footer — anchored just inside the bottom margin. Placing it below the margin
    // (or letting it wrap) makes pdfkit spill onto a spurious second page, so keep
    // it within bounds and disable line breaking.
    const footerY = doc.page.height - PAGE_MARGIN - 12;
    doc
      .fontSize(8)
      .font('Helvetica')
      .fillColor('#888')
      .text(t.footer(config.appName, new Date().toISOString()), PAGE_MARGIN, footerY, {
        width: contentWidth,
        align: 'center',
        lineBreak: false,
      });
    doc.fillColor('black');

    doc.end();
  });
}
