import type { ServerRoute } from '@hapi/hapi';
import {
  adminDeleteAssetImageRoute,
  adminGetAssetImageRoute,
  adminUploadAssetImageRoute,
} from './admin/assets/assetImage.route';
import { adminGetAssetQrRoute } from './admin/assets/assetQr.route';
import { adminBulkAssignRoute } from './admin/assetAssignments/assetAssignments.route';
import {
  adminDeleteCustodyDocumentRoute,
  adminGenerateBatchCustodyDocumentRoute,
  adminGenerateCustodyDocumentRoute,
  adminGetCustodyDocumentFileRoute,
  adminGetCustodyDocumentRoute,
  adminListCustodyDocumentsRoute,
  adminUploadCustodyDocumentRoute,
} from './admin/assets/custodyDocuments/custodyDocuments.route';
import {
  adminCreateAssetRoute,
  adminDeleteAssetRoute,
  adminGetAssetDetailsRoute,
  adminListAssetMapMarkersRoute,
  adminListAssetTransactionsRoute,
  adminListAssetsRoute,
  adminUpdateAssetRoute,
} from './admin/assets/assets.route';
import {
  adminCreateCategoryRoute,
  adminDeleteCategoryRoute,
  adminGetCategoryDetailsRoute,
  adminListCategoriesRoute,
  adminUpdateCategoryRoute,
} from './admin/categories/categories.route';
import {
  adminDeleteManufacturerImageRoute,
  adminGetManufacturerImageRoute,
  adminUploadManufacturerImageRoute,
} from './admin/manufacturers/manufacturerImage.route';
import {
  adminCreateManufacturerRoute,
  adminDeleteManufacturerRoute,
  adminGetManufacturerDetailsRoute,
  adminListManufacturersRoute,
  adminUpdateManufacturerRoute,
} from './admin/manufacturers/manufacturers.route';
import {
  adminCreateSiteRoute,
  adminDeleteSiteRoute,
  adminGetSiteDetailsRoute,
  adminListSiteAssetsRoute,
  adminListSitesRoute,
  adminUpdateSiteRoute,
} from './admin/sites/sites.route';
import {
  adminDeleteVendorImageRoute,
  adminGetVendorImageRoute,
  adminUploadVendorImageRoute,
} from './admin/vendors/vendorImage.route';
import {
  adminCreateVendorRoute,
  adminDeleteVendorRoute,
  adminGetVendorDetailsRoute,
  adminListVendorsRoute,
  adminUpdateVendorRoute,
} from './admin/vendors/vendors.route';
import { adminListAlertsRoute } from './admin/alerts/alerts.route';
import {
  adminCancelHandoverRoute,
  adminCompleteHandoverRoute,
  adminCreateHandoverRoute,
  adminGetHandoverRoute,
  adminListHandoversRoute,
  adminListOpenHandoversRoute,
} from './admin/handovers/handovers.route';
import { myHandoverAcceptByIdRoute, myHandoverAcceptRoute, myHandoverPreviewRoute, myHandoversListRoute } from './me/handovers/meHandovers.route';
import {
  adminDataQualityReportRoute,
  adminDismissDataQualityRoute,
  adminRestoreDataQualityRoute,
} from './admin/reports/reports.route';
import { adminStatsOverviewRoute } from './admin/stats/stats.route';
import { adminListTransactionsRoute } from './admin/transactions/transactions.route';
import {
  adminCreateApiKeyRoute,
  adminGetApiKeyRoute,
  adminListApiAccessLogsRoute,
  adminListApiKeysRoute,
  adminRegenerateApiKeyRoute,
  adminRevokeApiKeyRoute,
} from './admin/apiKeys/apiKeys.route';
import {
  adminCreateWebhookDestinationRoute,
  adminDeleteWebhookDestinationRoute,
  adminGetWebhookDestinationRoute,
  adminListWebhookDestinationsRoute,
  adminGetWebhookPlatformIconRoute,
  adminListWebhookEventsRoute,
  adminTestWebhookDestinationRoute,
  adminUpdateWebhookDestinationRoute,
} from './admin/webhooks/webhooks.route';
import {
  adminChangeUserPasswordRoute,
  adminCreateUserRoute,
  adminDeleteUserRoute,
  adminGetUserDetailsRoute,
  adminListUserAssetsRoute,
  adminListUserTransactionsRoute,
  adminListUsersRoute,
  adminUpdateUserRoute,
} from './admin/users/users.route';
import {
  adminDeleteUserAvatarRoute,
  adminUploadUserAvatarRoute,
  deleteMyAvatarRoute,
  getUserAvatarRoute,
  uploadMyAvatarRoute,
} from './avatar/avatar.route';
import { myAssetsRoute, myGetManufacturerImageRoute, myTransactionsRoute } from './me/me.route';
import { defaultRoute } from './default.route';
import { healthLivenessRoute, healthReadinessRoute } from './health/health.route';
import {
  sessionLoginRoute,
  sessionLogoutRoute,
  sessionMeRoute,
  sessionPublicConfigRoute,
} from './session/session.route';
import { passwordForgotRoute, passwordResetRoute } from './users/passwordReset/passwordReset.route';
import {
  registrationRegisterRoute,
  registrationResendVerificationRoute,
  registrationVerifyEmailRoute,
} from './users/registration/registration.route';
import {
  usersChangePasswordRoute,
  usersDeleteAccountRoute,
  usersUpdateProfileRoute,
} from './users/users.route';
import {
  adminCancelImportJobRoute,
  adminCommitImportJobRoute,
  adminCreateExportJobRoute,
  adminCreateImportJobRoute,
  adminCreateImportPresetRoute,
  adminDeleteImportPresetRoute,
  adminDownloadExportJobRoute,
  adminDryRunImportJobRoute,
  adminGetExportJobRoute,
  adminGetImportJobErrorsRoute,
  adminGetImportJobRoute,
  adminGetImportTemplateRoute,
  adminListExportJobsRoute,
  adminListJobHistoryRoute,
  adminListImportJobRowsRoute,
  adminListImportJobsRoute,
  adminListImportPresetsRoute,
  adminSetImportMappingRoute,
} from './admin/importExport/importExport.route';

export const routes: ServerRoute[] = [
  adminListUsersRoute,
  adminGetUserDetailsRoute,
  adminCreateUserRoute,
  adminUpdateUserRoute,
  adminChangeUserPasswordRoute,
  adminDeleteUserRoute,
  adminListUserAssetsRoute,
  adminListUserTransactionsRoute,
  adminListAssetsRoute,
  adminListAssetMapMarkersRoute,
  adminGetAssetDetailsRoute,
  adminCreateAssetRoute,
  adminUpdateAssetRoute,
  adminDeleteAssetRoute,
  adminListAssetTransactionsRoute,
  adminBulkAssignRoute,
  adminUploadAssetImageRoute,
  adminDeleteAssetImageRoute,
  adminGetAssetImageRoute,
  adminListCustodyDocumentsRoute,
  adminUploadCustodyDocumentRoute,
  adminGenerateCustodyDocumentRoute,
  adminGenerateBatchCustodyDocumentRoute,
  adminGetCustodyDocumentRoute,
  adminGetCustodyDocumentFileRoute,
  adminDeleteCustodyDocumentRoute,
  adminGetAssetQrRoute,
  adminListManufacturersRoute,
  adminGetManufacturerDetailsRoute,
  adminCreateManufacturerRoute,
  adminUpdateManufacturerRoute,
  adminDeleteManufacturerRoute,
  adminUploadManufacturerImageRoute,
  adminDeleteManufacturerImageRoute,
  adminGetManufacturerImageRoute,
  adminListCategoriesRoute,
  adminGetCategoryDetailsRoute,
  adminCreateCategoryRoute,
  adminUpdateCategoryRoute,
  adminDeleteCategoryRoute,
  adminListVendorsRoute,
  adminGetVendorDetailsRoute,
  adminCreateVendorRoute,
  adminUpdateVendorRoute,
  adminDeleteVendorRoute,
  adminUploadVendorImageRoute,
  adminDeleteVendorImageRoute,
  adminGetVendorImageRoute,
  adminListSitesRoute,
  adminGetSiteDetailsRoute,
  adminCreateSiteRoute,
  adminUpdateSiteRoute,
  adminDeleteSiteRoute,
  adminListSiteAssetsRoute,
  adminStatsOverviewRoute,
  adminDataQualityReportRoute,
  adminDismissDataQualityRoute,
  adminRestoreDataQualityRoute,
  adminListAlertsRoute,
  adminListTransactionsRoute,
  adminCreateApiKeyRoute,
  adminListApiKeysRoute,
  adminGetApiKeyRoute,
  adminRegenerateApiKeyRoute,
  adminRevokeApiKeyRoute,
  adminListApiAccessLogsRoute,
  adminListWebhookEventsRoute,
  adminListWebhookDestinationsRoute,
  adminGetWebhookDestinationRoute,
  adminCreateWebhookDestinationRoute,
  adminUpdateWebhookDestinationRoute,
  adminDeleteWebhookDestinationRoute,
  adminTestWebhookDestinationRoute,
  adminGetWebhookPlatformIconRoute,
  adminListOpenHandoversRoute,
  adminCreateHandoverRoute,
  adminListHandoversRoute,
  adminGetHandoverRoute,
  adminCancelHandoverRoute,
  adminCompleteHandoverRoute,
  myHandoversListRoute,
  myHandoverPreviewRoute,
  myHandoverAcceptRoute,
  myHandoverAcceptByIdRoute,
  myAssetsRoute,
  myGetManufacturerImageRoute,
  myTransactionsRoute,
  uploadMyAvatarRoute,
  deleteMyAvatarRoute,
  getUserAvatarRoute,
  adminUploadUserAvatarRoute,
  adminDeleteUserAvatarRoute,
  sessionPublicConfigRoute,
  sessionLoginRoute,
  sessionLogoutRoute,
  sessionMeRoute,
  registrationRegisterRoute,
  registrationVerifyEmailRoute,
  registrationResendVerificationRoute,
  passwordForgotRoute,
  passwordResetRoute,
  usersChangePasswordRoute,
  usersUpdateProfileRoute,
  usersDeleteAccountRoute,
  adminCreateImportJobRoute,
  adminSetImportMappingRoute,
  adminDryRunImportJobRoute,
  adminCommitImportJobRoute,
  adminCancelImportJobRoute,
  adminListImportJobsRoute,
  adminGetImportJobRoute,
  adminListImportJobRowsRoute,
  adminGetImportJobErrorsRoute,
  adminCreateExportJobRoute,
  adminListExportJobsRoute,
  adminListJobHistoryRoute,
  adminGetExportJobRoute,
  adminDownloadExportJobRoute,
  adminListImportPresetsRoute,
  adminCreateImportPresetRoute,
  adminDeleteImportPresetRoute,
  adminGetImportTemplateRoute,
  defaultRoute,
  healthLivenessRoute,
  healthReadinessRoute,
];
